import { Redirect } from "expo-router";


export default function Index() {
  // Redirect to the drawer screen route generated by expo-router.
  // Use `/drawer/Acceuil` (matches the file `app/drawer/Acceuil.tsx`) instead of `/Screen/...`.
  return <Redirect href={"/drawer/DrawerNav"}/>
}
